#!/usr/bin/env python3
"""Generate tests/Ttfx.Tests/fixtures/numeric_corpus.txt from the Rust parsers.

Feeds a token list to:
  1. a rustc-built `str::parse` probe (i64 / u64 / f64)
  2. reference/ttfx for --tab-width, --frame-rate, --canvas-width, --seed

Never resolves `ttfx` from PATH. Re-run from the repo root after changing TOKENS.
"""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
REF = ROOT / "reference" / "ttfx"
PROBE_SRC = Path(__file__).resolve().parent / "parsedump.rs"
OUT = ROOT / "tests" / "Ttfx.Tests" / "fixtures" / "numeric_corpus.txt"

TOKENS = [
    "4",
    " 4 ",
    "4 ",
    " 4",
    "+4",
    "0",
    "-1",
    "-2",
    "00",
    "1.0",
    "inf",
    "Inf",
    "INF",
    "infinity",
    "Infinity",
    "INFINITY",
    "+inf",
    "-inf",
    "+infinity",
    "-infinity",
    "NaN",
    "nan",
    "NAN",
    "+nan",
    "-nan",
    "+NaN",
    "-NaN",
    "",
    "0x10",
    "0x4",
    "1_000",
    "1_0",
    "-0",
    "+0",
    "256",
    "255",
    "-256",
    "9223372036854775807",
    "9223372036854775808",
    "-9223372036854775808",
    "-9223372036854775809",
    "18446744073709551615",
    "18446744073709551616",
    "1e400",
    "1e-400",
    "1e2",
    "1E2",
    "1e+2",
    "1e-2",
    "4.0",
    "4.5",
    "+1.5",
    "-1.5",
    "0.0",
    "-0.0",
    "00.0",
    ".5",
    "5.",
    ".",
    "+",
    "-",
    "++4",
    "--4",
    "4foo",
    "+ 4",
    "0o4",
    "0b1",
    "1,000",
    "1.0.0",
    "e10",
    "1e",
    "1e+",
    "1e-",
    " ",
    "\t4",
    "4\n",
    "\n4",
    "4\t",
    "\u00a04",
    "∞",
    "Infinity ",
    " inf",
    "inf ",
    "3.14e-2",
    "1E-10",
    "0004",
    "+00",
    "-00",
    "0.",
    ".0",
    "0e0",
    "0e-0",
    "+.5",
    "-.5",
    "5.e2",
    ".e2",
    "1e4000",
    "-1e4000",
    "2.2250738585072014e-308",
    "1.7976931348623157e+308",
    "1.7976931348623157e+309",
]


def hex_token(token: str) -> str:
    return token.encode("utf-8").hex()


def compile_probe(dest: Path) -> None:
    subprocess.check_call(["rustc", "-O", "-o", str(dest), str(PROBE_SRC)])


def run_probe(probe: Path, kind: str, token: str) -> str:
    r = subprocess.run(
        [str(probe), kind, token],
        capture_output=True,
        text=True,
        check=False,
    )
    if r.returncode != 0:
        raise SystemExit(f"parsedump {kind!r} failed for {token!r}: {r.stderr}")
    return r.stdout.strip()


def run_cli(option: str, token: str) -> tuple[str, int]:
    r = subprocess.run(
        [str(REF), f"--{option}", token, "--print-completion", "bash"],
        capture_output=True,
        text=True,
        check=False,
    )
    rc = r.returncode
    if rc == 0:
        return "accept", rc
    return "reject", rc


def main() -> int:
    if not REF.is_file():
        print(
            "reference/ttfx is missing. Run tools/parity/fetch_reference.sh first.",
            file=sys.stderr,
        )
        return 1

    probe = Path("/tmp/ttfx-parsedump")
    compile_probe(probe)

    lines: list[str] = [
        "# numeric_corpus.txt — generated by tools/tests/gen_numeric_corpus.py",
        "# Do not hand-edit. Columns are tab-separated:",
        "#   rust <i64|u64|f64> <token_utf8_hex> <accept|reject> [payload]",
        "#   cli  <option>      <token_utf8_hex> <accept|reject> <exit_code>",
        "# payload for i64/u64 is the decimal value; for f64 it is to_bits() hex.",
        "# The 37-effect registry count is asserted in a later issue, not here.",
    ]

    for kind in ("i64", "u64", "f64"):
        for token in TOKENS:
            result = run_probe(probe, kind, token)
            parts = result.split()
            status = parts[0]
            payload = parts[1] if len(parts) > 1 else ""
            extra = f"\t{payload}" if payload else ""
            lines.append(f"rust\t{kind}\t{hex_token(token)}\t{status}{extra}")

    for option in ("tab-width", "frame-rate", "canvas-width", "seed"):
        for token in TOKENS:
            status, rc = run_cli(option, token)
            lines.append(f"cli\t{option}\t{hex_token(token)}\t{status}\t{rc}")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({len(lines)} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
