using System;
using System.Collections.Generic;
using Ttfx.Cli;
using Ttfx.Engine;

namespace Ttfx.Effects;

public sealed record EffectSpec(
    string Name,
    string Description,
    OptionSpec[] Options,
    Func<Dictionary<string, object>, IEffect>? Factory = null);

/// <summary>
/// Static name → option specs + factory. Enumeration order is observable:
/// <c>--random-effect</c> selects by <c>ChoiceIndex(names.Count)</c>, so the
/// list matches the reference EffectCommand order exactly.
/// <c>--probe</c> is a root flag, not a registry entry.
/// </summary>
public static class EffectRegistry
{
    public static EffectSpec[] Effects { get; } =
    [
        new EffectSpec(
            "beams",
            "Create beams which travel over the canvas illuminating the characters behind them.",
            [
                new OptionSpec(
                    "--beam-row-symbols",
                    null,
                    "SYMBOL",
                    "Symbols to use for the beam effect when moving along a row. Strings will be used in sequence to create an animation.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseSymbol,
                    DefaultValues: ["▂", "▁", "_"]),
                new OptionSpec(
                    "--beam-column-symbols",
                    null,
                    "SYMBOL",
                    "Symbols to use for the beam effect when moving along a column. Strings will be used in sequence to create an animation.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseSymbol,
                    DefaultValues: ["▌", "▍", "▎", "▏"]),
                new OptionSpec(
                    "--beam-delay",
                    null,
                    "DELAY",
                    "Number of frames to wait before adding the next group of beams. Beams are added in groups of size random(1, 5).",
                    OptionArity.One,
                    "6",
                    ValueParsers.ParseCommonPositiveInt),
                new OptionSpec(
                    "--beam-row-speed-range",
                    null,
                    "RANGE",
                    "Speed range of the beam when moving along a row.",
                    OptionArity.One,
                    "15-60",
                    ValueParsers.ParsePositiveIntRange),
                new OptionSpec(
                    "--beam-column-speed-range",
                    null,
                    "RANGE",
                    "Speed range of the beam when moving along a column.",
                    OptionArity.One,
                    "9-15",
                    ValueParsers.ParsePositiveIntRange),
                new OptionSpec(
                    "--beam-gradient-stops",
                    null,
                    "COLOR",
                    "Space separated, unquoted, list of colors for the beam, a gradient will be created between the colors.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseColorArg,
                    DefaultValues: ["ffffff", "00D1FF", "8A008A"]),
                new OptionSpec(
                    "--beam-gradient-steps",
                    null,
                    "STEPS",
                    "Space separated, unquoted, numbers for the of gradient steps to use.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseGradientSteps,
                    DefaultValues: ["2", "6"]),
                new OptionSpec(
                    "--beam-gradient-frames",
                    null,
                    "FRAMES",
                    "Number of frames to display each gradient step. Increase to slow down the gradient animation.",
                    OptionArity.One,
                    "2",
                    ValueParsers.ParseCommonPositiveInt),
                new OptionSpec(
                    "--final-gradient-stops",
                    null,
                    "COLOR",
                    "Space separated, unquoted, list of colors for the wipe gradient.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseColorArg,
                    DefaultValues: ["8A008A", "00D1FF", "ffffff"]),
                new OptionSpec(
                    "--final-gradient-steps",
                    null,
                    "STEPS",
                    "Number of gradient steps to use.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseGradientSteps,
                    DefaultValues: ["12"]),
                new OptionSpec(
                    "--final-gradient-frames",
                    null,
                    "FRAMES",
                    "Number of frames to display each gradient step. Increase to slow down the gradient animation.",
                    OptionArity.One,
                    "4",
                    ValueParsers.ParseCommonPositiveInt),
                new OptionSpec(
                    "--final-gradient-direction",
                    null,
                    "DIRECTION",
                    "Direction of the final gradient.",
                    OptionArity.One,
                    "vertical",
                    ValueParsers.ParseGradientDirection),
                new OptionSpec(
                    "--final-wipe-speed",
                    null,
                    "SPEED",
                    "Speed of the final wipe as measured in diagonal groups activated per frame.",
                    OptionArity.One,
                    "3",
                    ValueParsers.ParseCommonPositiveInt),
            ],
            Beams.FromOptions),
        new EffectSpec(
            "binarypath",
            "Binary representations of each character move towards the home coordinate of the character.",
            [
                new OptionSpec(
                    "--final-gradient-stops",
                    null,
                    "COLOR",
                    "Space separated, unquoted, list of colors for the final color gradient.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseColorArg,
                    DefaultValues: ["00d500", "007500"]),
                new OptionSpec(
                    "--final-gradient-steps",
                    null,
                    "STEPS",
                    "Number of gradient steps to use.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseGradientSteps,
                    DefaultValues: ["12"]),
                new OptionSpec(
                    "--final-gradient-direction",
                    null,
                    "DIRECTION",
                    "Direction of the final gradient.",
                    OptionArity.One,
                    "radial",
                    ValueParsers.ParseGradientDirection),
                new OptionSpec(
                    "--binary-colors",
                    null,
                    "COLOR",
                    "Space separated, unquoted, list of colors for the binary characters. Character color is randomly assigned from this list.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseColorArg,
                    DefaultValues: ["044E29", "157e38", "45bf55", "95ed87"]),
                new OptionSpec(
                    "--movement-speed",
                    null,
                    "SPEED",
                    "Speed of the binary groups as they travel around the terminal.",
                    OptionArity.One,
                    "1.0",
                    ValueParsers.ParsePositiveFloat),
                new OptionSpec(
                    "--active-binary-groups",
                    null,
                    "RATIO",
                    "Maximum number of binary groups that are active at any given time as a percentage of the total number of binary groups. Lower this to improve performance.",
                    OptionArity.One,
                    "0.08",
                    ValueParsers.ParseNonNegativeRatio),
            ],
            BinaryPath.FromOptions),
        new EffectSpec(
            "blackhole",
            "Characters are consumed by a black hole and explode outwards.",
            [
                new OptionSpec(
                    "--blackhole-color",
                    null,
                    "COLOR",
                    "Color for the stars that comprise the blackhole border.",
                    OptionArity.One,
                    "ffffff",
                    ValueParsers.ParseColorArg),
                new OptionSpec(
                    "--star-colors",
                    null,
                    "COLOR",
                    "List of colors from which character colors will be chosen and applied after the explosion, but before the cooldown to final color.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseColorArg,
                    DefaultValues: ["ffcc0d", "ff7326", "ff194d", "bf2669", "702a8c", "049dbf"]),
                new OptionSpec(
                    "--final-gradient-stops",
                    null,
                    "COLOR",
                    "Space separated, unquoted, list of colors for the final color gradient.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseColorArg,
                    DefaultValues: ["8A008A", "00D1FF", "ffffff"]),
                new OptionSpec(
                    "--final-gradient-steps",
                    null,
                    "STEPS",
                    "Number of gradient steps to use.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseGradientSteps,
                    DefaultValues: ["9"]),
                new OptionSpec(
                    "--final-gradient-direction",
                    null,
                    "DIRECTION",
                    "Direction of the final gradient.",
                    OptionArity.One,
                    "diagonal",
                    ValueParsers.ParseGradientDirection),
            ],
            Blackhole.FromOptions),
        new EffectSpec(
            "bouncyballs",
            "Characters are bouncy balls falling from the top of the canvas.",
            [
                new OptionSpec(
                    "--ball-colors",
                    null,
                    "COLOR",
                    "Space separated list of colors from which ball colors will be randomly selected.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseColorArg,
                    DefaultValues: ["d1f4a5", "96e2a4", "5acda9"]),
                new OptionSpec(
                    "--ball-symbols",
                    null,
                    "SYMBOL",
                    "Space separated list of symbols to use for the balls.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseSymbol,
                    DefaultValues: ["*", "o", "O", "0", "."]),
                new OptionSpec(
                    "--ball-delay",
                    null,
                    "DELAY",
                    "Number of frames between ball drops, increase to reduce ball drop rate.",
                    OptionArity.One,
                    "4",
                    ValueParsers.ParseCommonNonNegativeInt),
                new OptionSpec(
                    "--movement-speed",
                    null,
                    "SPEED",
                    "Movement speed of the characters.",
                    OptionArity.One,
                    "0.45",
                    ValueParsers.ParsePositiveFloat),
                new OptionSpec(
                    "--movement-easing",
                    null,
                    "EASE",
                    "Easing function to use for character movement.",
                    OptionArity.One,
                    "out_bounce",
                    ValueParsers.ParseEasingName),
                new OptionSpec(
                    "--final-gradient-stops",
                    null,
                    "COLOR",
                    "Space separated, unquoted, list of colors for the final color gradient.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseColorArg,
                    DefaultValues: ["f8ffae", "43c6ac"]),
                new OptionSpec(
                    "--final-gradient-steps",
                    null,
                    "STEPS",
                    "Number of gradient steps to use.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseGradientSteps,
                    DefaultValues: ["12"]),
                new OptionSpec(
                    "--final-gradient-direction",
                    null,
                    "DIRECTION",
                    "Direction of the final gradient.",
                    OptionArity.One,
                    "diagonal",
                    ValueParsers.ParseGradientDirection),
            ],
            BouncyBalls.FromOptions),
        new EffectSpec(
            "bubbles",
            "Characters are formed into bubbles that float down and pop.",
            [
                new OptionSpec(
                    "--rainbow",
                    null,
                    "",
                    "If set, the bubbles will be colored with a rotating rainbow gradient.",
                    OptionArity.Flag,
                    null,
                    _ => true),
                new OptionSpec(
                    "--bubble-colors",
                    null,
                    "COLOR",
                    "Space separated, unquoted, list of colors for the bubbles. Ignored if --no-rainbow is left as default False.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseColorArg,
                    DefaultValues: ["d33aff", "7395c4", "43c2a7", "02ff7f"]),
                new OptionSpec(
                    "--pop-color",
                    null,
                    "COLOR",
                    "Color for the spray emitted when a bubble pops.",
                    OptionArity.One,
                    "ffffff",
                    ValueParsers.ParseColorArg),
                new OptionSpec(
                    "--bubble-speed",
                    null,
                    "SPEED",
                    "Speed of the floating bubbles.",
                    OptionArity.One,
                    "0.5",
                    ValueParsers.ParsePositiveFloat),
                new OptionSpec(
                    "--bubble-delay",
                    null,
                    "DELAY",
                    "Number of frames between bubbles.",
                    OptionArity.One,
                    "20",
                    ValueParsers.ParseCommonPositiveInt),
                new OptionSpec(
                    "--pop-condition",
                    null,
                    "CONDITION",
                    "Condition for a bubble to pop.",
                    OptionArity.One,
                    "row",
                    Bubbles.ParsePopCondition),
                new OptionSpec(
                    "--movement-easing",
                    null,
                    "EASE",
                    "Easing function to use for character movement after a bubble pops.",
                    OptionArity.One,
                    "in_out_sine",
                    ValueParsers.ParseEasingName),
                new OptionSpec(
                    "--final-gradient-stops",
                    null,
                    "COLOR",
                    "Space separated, unquoted, list of colors for the final color gradient.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseColorArg,
                    DefaultValues: ["d33aff", "02ff7f"]),
                new OptionSpec(
                    "--final-gradient-steps",
                    null,
                    "STEPS",
                    "Number of gradient steps to use.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseGradientSteps,
                    DefaultValues: ["12"]),
                new OptionSpec(
                    "--final-gradient-direction",
                    null,
                    "DIRECTION",
                    "Direction of the final gradient.",
                    OptionArity.One,
                    "diagonal",
                    ValueParsers.ParseGradientDirection),
            ],
            Bubbles.FromOptions),
        Stub("burn", "Burns vertically in the canvas."),
        new EffectSpec(
            "colorshift",
            "Display a gradient that shifts colors across the terminal.",
            [
                new OptionSpec(
                    "--gradient-stops",
                    null,
                    "COLOR",
                    "Space separated, unquoted, list of colors for the gradient.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseColorArg,
                    DefaultValues: ["e81416", "ffa500", "faeb36", "79c314", "487de7", "4b369d", "70369d"]),
                new OptionSpec(
                    "--gradient-steps",
                    null,
                    "STEPS",
                    "Number of gradient steps to use. More steps will create a smoother gradient animation.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseGradientSteps,
                    DefaultValues: ["12"]),
                new OptionSpec(
                    "--gradient-frames",
                    null,
                    "FRAMES",
                    "Number of frames to display each gradient step. Increase to slow down the gradient animation.",
                    OptionArity.One,
                    "2",
                    ValueParsers.ParseCommonPositiveInt),
                new OptionSpec(
                    "--no-travel",
                    null,
                    "",
                    "Do not display the gradient as a wave.",
                    OptionArity.Flag,
                    null,
                    _ => true),
                new OptionSpec(
                    "--travel-direction",
                    null,
                    "DIRECTION",
                    "Direction the gradient travels across the canvas.",
                    OptionArity.One,
                    "radial",
                    ValueParsers.ParseGradientDirection),
                new OptionSpec(
                    "--reverse-travel-direction",
                    null,
                    "",
                    "Reverse the gradient travel direction.",
                    OptionArity.Flag,
                    null,
                    _ => true),
                new OptionSpec(
                    "--no-loop",
                    null,
                    "",
                    "Do not loop the gradient.",
                    OptionArity.Flag,
                    null,
                    _ => true),
                new OptionSpec(
                    "--cycles",
                    null,
                    "CYCLES",
                    "Number of times to cycle the gradient.",
                    OptionArity.One,
                    "3",
                    ValueParsers.ParseCommonPositiveInt),
                new OptionSpec(
                    "--skip-final-gradient",
                    null,
                    "",
                    "Skip the final gradient.",
                    OptionArity.Flag,
                    null,
                    _ => true),
                new OptionSpec(
                    "--final-gradient-stops",
                    null,
                    "COLOR",
                    "Space separated, unquoted, list of colors for the final color gradient.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseColorArg,
                    DefaultValues: ["e81416", "ffa500", "faeb36", "79c314", "487de7", "4b369d", "70369d"]),
                new OptionSpec(
                    "--final-gradient-steps",
                    null,
                    "STEPS",
                    "Number of gradient steps to use for the final gradient.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseGradientSteps,
                    DefaultValues: ["12"]),
                new OptionSpec(
                    "--final-gradient-direction",
                    null,
                    "DIRECTION",
                    "Direction of the final gradient.",
                    OptionArity.One,
                    "vertical",
                    ValueParsers.ParseGradientDirection),
            ],
            ColorShift.FromOptions),
        new EffectSpec(
            "crumble",
            "Characters lose color and crumble into dust, vacuumed up, and reformed.",
            [
                new OptionSpec(
                    "--final-gradient-stops",
                    null,
                    "COLOR",
                    "Space separated, unquoted, list of colors for the final color gradient.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseColorArg,
                    DefaultValues: ["5CE1FF", "FF8C00"]),
                new OptionSpec(
                    "--final-gradient-steps",
                    null,
                    "STEPS",
                    "Number of gradient steps to use.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseGradientSteps,
                    DefaultValues: ["12"]),
                new OptionSpec(
                    "--final-gradient-direction",
                    null,
                    "DIRECTION",
                    "Direction of the final gradient.",
                    OptionArity.One,
                    "diagonal",
                    ValueParsers.ParseGradientDirection),
            ],
            Crumble.FromOptions),
        new EffectSpec(
            "decrypt",
            "Display a movie style decryption effect.",
            [
                new OptionSpec(
                    "--typing-speed",
                    null,
                    "SPEED",
                    "Number of characters typed per keystroke.",
                    OptionArity.One,
                    "2",
                    ValueParsers.ParseCommonPositiveInt),
                new OptionSpec(
                    "--ciphertext-colors",
                    null,
                    "COLOR",
                    "Space separated, unquoted, list of colors for the ciphertext. Color will be randomly selected for each character.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseColorArg,
                    DefaultValues: ["008000", "00cb00", "00ff00"]),
                new OptionSpec(
                    "--final-gradient-stops",
                    null,
                    "COLOR",
                    "Space separated, unquoted, list of colors for the character gradient.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseColorArg,
                    DefaultValues: ["eda000"]),
                new OptionSpec(
                    "--final-gradient-steps",
                    null,
                    "STEPS",
                    "Number of gradient steps to use.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseGradientSteps,
                    DefaultValues: ["12"]),
                new OptionSpec(
                    "--final-gradient-direction",
                    null,
                    "DIRECTION",
                    "Direction of the final gradient.",
                    OptionArity.One,
                    "vertical",
                    ValueParsers.ParseGradientDirection),
            ],
            Decrypt.FromOptions),
        new EffectSpec(
            "errorcorrect",
            "Some characters start in the wrong position and are corrected in sequence.",
            [
                new OptionSpec(
                    "--error-pairs",
                    null,
                    "PAIRS",
                    "Percent of characters that are in the wrong position. This is a float between 0 and 1.0.",
                    OptionArity.One,
                    "0.1",
                    ValueParsers.ParsePositiveFloat),
                new OptionSpec(
                    "--swap-delay",
                    null,
                    "DELAY",
                    "Number of frames between swaps.",
                    OptionArity.One,
                    "6",
                    ValueParsers.ParseCommonPositiveInt),
                new OptionSpec(
                    "--error-color",
                    null,
                    "COLOR",
                    "Color for the characters that are in the wrong position.",
                    OptionArity.One,
                    "e74c3c",
                    ValueParsers.ParseColorArg),
                new OptionSpec(
                    "--correct-color",
                    null,
                    "COLOR",
                    "Color for the characters once corrected, this is a gradient from error-color and fades to final-color.",
                    OptionArity.One,
                    "45bf55",
                    ValueParsers.ParseColorArg),
                new OptionSpec(
                    "--movement-speed",
                    null,
                    "SPEED",
                    "Speed of the characters while moving to the correct position.",
                    OptionArity.One,
                    "0.9",
                    ValueParsers.ParsePositiveFloat),
                new OptionSpec(
                    "--final-gradient-stops",
                    null,
                    "COLOR",
                    "Space separated, unquoted, list of colors for the final color gradient.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseColorArg,
                    DefaultValues: ["8A008A", "00D1FF", "FFFFFF"]),
                new OptionSpec(
                    "--final-gradient-steps",
                    null,
                    "STEPS",
                    "Number of gradient steps to use.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseGradientSteps,
                    DefaultValues: ["12"]),
                new OptionSpec(
                    "--final-gradient-direction",
                    null,
                    "DIRECTION",
                    "Direction of the final gradient.",
                    OptionArity.One,
                    "vertical",
                    ValueParsers.ParseGradientDirection),
            ],
            ErrorCorrect.FromOptions),
        new EffectSpec(
            "expand",
            "Expands the text from a single point.",
            [
                new OptionSpec(
                    "--expand-easing",
                    null,
                    "EASE",
                    "Easing function to use for character movement.",
                    OptionArity.One,
                    "in_out_quart",
                    ValueParsers.ParseEasingName),
                new OptionSpec(
                    "--movement-speed",
                    null,
                    "SPEED",
                    "Movement speed of the characters.",
                    OptionArity.One,
                    "0.35",
                    ValueParsers.ParsePositiveFloat),
                new OptionSpec(
                    "--final-gradient-stops",
                    null,
                    "COLOR",
                    "Space separated, unquoted, list of colors for the final color gradient.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseColorArg,
                    DefaultValues: ["8A008A", "00D1FF", "FFFFFF"]),
                new OptionSpec(
                    "--final-gradient-steps",
                    null,
                    "STEPS",
                    "Number of gradient steps to use.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseGradientSteps,
                    DefaultValues: ["12"]),
                new OptionSpec(
                    "--final-gradient-direction",
                    null,
                    "DIRECTION",
                    "Direction of the final gradient.",
                    OptionArity.One,
                    "vertical",
                    ValueParsers.ParseGradientDirection),
            ],
            Expand.FromOptions),
        new EffectSpec(
            "fireworks",
            "Characters launch and explode like fireworks and fall into place.",
            [
                new OptionSpec(
                    "--explode-anywhere",
                    null,
                    "",
                    "If set, fireworks explode anywhere in the canvas. Otherwise, fireworks explode above highest settled row of text.",
                    OptionArity.Flag,
                    null,
                    _ => true),
                new OptionSpec(
                    "--firework-colors",
                    null,
                    "COLOR",
                    "Space separated list of colors from which firework colors will be randomly selected.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseColorArg,
                    DefaultValues: ["88F7E2", "44D492", "F5EB67", "FFA15C", "FA233E"]),
                new OptionSpec(
                    "--firework-symbol",
                    null,
                    "SYMBOL",
                    "Symbol to use for the firework shell.",
                    OptionArity.One,
                    "o",
                    ValueParsers.ParseSymbol),
                new OptionSpec(
                    "--firework-volume",
                    null,
                    "RATIO",
                    "Percent of total characters in each firework shell.",
                    OptionArity.One,
                    "0.05",
                    ValueParsers.ParseNonNegativeRatio),
                new OptionSpec(
                    "--launch-delay",
                    null,
                    "DELAY",
                    "Number of frames to wait between launching each firework shell. +/- 0-50 percent randomness is applied to this value.",
                    OptionArity.One,
                    "45",
                    ValueParsers.ParseNonNegativeInt),
                new OptionSpec(
                    "--explode-distance",
                    null,
                    "RATIO",
                    "Maximum distance from the firework shell origin to the explode waypoint as a percentage of the total canvas width.",
                    OptionArity.One,
                    "0.2",
                    ValueParsers.ParseNonNegativeRatio),
                new OptionSpec(
                    "--final-gradient-stops",
                    null,
                    "COLOR",
                    "Space separated, unquoted, list of colors for the final color gradient.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseColorArg,
                    DefaultValues: ["8A008A", "00D1FF", "FFFFFF"]),
                new OptionSpec(
                    "--final-gradient-steps",
                    null,
                    "STEPS",
                    "Number of gradient steps to use.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseGradientSteps,
                    DefaultValues: ["12"]),
                new OptionSpec(
                    "--final-gradient-direction",
                    null,
                    "DIRECTION",
                    "Direction of the final gradient.",
                    OptionArity.One,
                    "horizontal",
                    ValueParsers.ParseGradientDirection),
            ],
            Fireworks.FromOptions),
        new EffectSpec(
            "highlight",
            "Run a specular highlight across the text.",
            [
                new OptionSpec(
                    "--highlight-brightness",
                    null,
                    "BRIGHTNESS",
                    "Brightness of the highlight color.",
                    OptionArity.One,
                    "1.75",
                    ValueParsers.ParsePositiveFloat),
                new OptionSpec(
                    "--highlight-direction",
                    null,
                    "DIRECTION",
                    "Direction the highlight will travel.",
                    OptionArity.One,
                    "diagonal_bottom_left_to_top_right",
                    ValueParsers.ParseCharacterGroup),
                new OptionSpec(
                    "--highlight-width",
                    null,
                    "WIDTH",
                    "Width of the highlight. n >= 1",
                    OptionArity.One,
                    "8",
                    ValueParsers.ParseCommonPositiveInt),
                new OptionSpec(
                    "--final-gradient-stops",
                    null,
                    "COLOR",
                    "Space separated, unquoted, list of colors for the final color gradient.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseColorArg,
                    DefaultValues: ["8A008A", "00D1FF", "FFFFFF"]),
                new OptionSpec(
                    "--final-gradient-steps",
                    null,
                    "STEPS",
                    "Number of gradient steps to use.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseGradientSteps,
                    DefaultValues: ["12"]),
                new OptionSpec(
                    "--final-gradient-direction",
                    null,
                    "DIRECTION",
                    "Direction of the final gradient.",
                    OptionArity.One,
                    "vertical",
                    ValueParsers.ParseGradientDirection),
            ],
            Highlight.FromOptions),
        Stub("laseretch", "A laser etches characters onto the terminal."),
        Stub("matrix", "Matrix digital rain effect."),
        new EffectSpec(
            "middleout",
            "Text expands in a single row or column in the middle of the canvas then out.",
            [
                new OptionSpec(
                    "--starting-color",
                    null,
                    "COLOR",
                    "Color for the initial text in the center of the canvas.",
                    OptionArity.One,
                    "ffffff",
                    ValueParsers.ParseColorArg),
                new OptionSpec(
                    "--expand-direction",
                    null,
                    "DIRECTION",
                    "Direction the text will expand.",
                    OptionArity.One,
                    "vertical",
                    Middleout.ParseExpandDirection),
                new OptionSpec(
                    "--center-movement-speed",
                    null,
                    "SPEED",
                    "Speed of the characters during the initial expansion of the center vertical/horiztonal line.",
                    OptionArity.One,
                    "0.6",
                    ValueParsers.ParsePositiveFloat),
                new OptionSpec(
                    "--full-movement-speed",
                    null,
                    "SPEED",
                    "Speed of the characters during the final full expansion.",
                    OptionArity.One,
                    "0.6",
                    ValueParsers.ParsePositiveFloat),
                new OptionSpec(
                    "--center-easing",
                    null,
                    "EASE",
                    "Easing function to use for initial expansion.",
                    OptionArity.One,
                    "in_out_sine",
                    ValueParsers.ParseEasingName),
                new OptionSpec(
                    "--full-easing",
                    null,
                    "EASE",
                    "Easing function to use for full expansion.",
                    OptionArity.One,
                    "in_out_sine",
                    ValueParsers.ParseEasingName),
                new OptionSpec(
                    "--final-gradient-stops",
                    null,
                    "COLOR",
                    "Space separated, unquoted, list of colors for the final color gradient.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseColorArg,
                    DefaultValues: ["8A008A", "00D1FF", "FFFFFF"]),
                new OptionSpec(
                    "--final-gradient-steps",
                    null,
                    "STEPS",
                    "Number of gradient steps to use.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseGradientSteps,
                    DefaultValues: ["12"]),
                new OptionSpec(
                    "--final-gradient-direction",
                    null,
                    "DIRECTION",
                    "Direction of the final gradient.",
                    OptionArity.One,
                    "vertical",
                    ValueParsers.ParseGradientDirection),
            ],
            Middleout.FromOptions),
        new EffectSpec(
            "orbittingvolley",
            "Four launchers orbit the canvas firing volleys of characters inward to build the input text from the center out.",
            [
                new OptionSpec(
                    "--top-launcher-symbol",
                    null,
                    "SYMBOL",
                    "Symbol for the top launcher.",
                    OptionArity.One,
                    "█",
                    ValueParsers.ParseSymbol),
                new OptionSpec(
                    "--right-launcher-symbol",
                    null,
                    "SYMBOL",
                    "Symbol for the right launcher.",
                    OptionArity.One,
                    "█",
                    ValueParsers.ParseSymbol),
                new OptionSpec(
                    "--bottom-launcher-symbol",
                    null,
                    "SYMBOL",
                    "Symbol for the bottom launcher.",
                    OptionArity.One,
                    "█",
                    ValueParsers.ParseSymbol),
                new OptionSpec(
                    "--left-launcher-symbol",
                    null,
                    "SYMBOL",
                    "Symbol for the left launcher.",
                    OptionArity.One,
                    "█",
                    ValueParsers.ParseSymbol),
                new OptionSpec(
                    "--launcher-movement-speed",
                    null,
                    "SPEED",
                    "Orbitting speed of the launchers.",
                    OptionArity.One,
                    "0.8",
                    ValueParsers.ParsePositiveFloat),
                new OptionSpec(
                    "--character-movement-speed",
                    null,
                    "SPEED",
                    "Speed of the launched characters.",
                    OptionArity.One,
                    "1.5",
                    ValueParsers.ParsePositiveFloat),
                new OptionSpec(
                    "--volley-size",
                    null,
                    "RATIO",
                    "Percent of total input characters each launcher will fire per volley. Lower limit of one character.",
                    OptionArity.One,
                    "0.03",
                    ValueParsers.ParseNonNegativeRatio),
                new OptionSpec(
                    "--launch-delay",
                    null,
                    "DELAY",
                    "Number of animation ticks to wait between volleys of characters.",
                    OptionArity.One,
                    "30",
                    ValueParsers.ParseNonNegativeInt),
                new OptionSpec(
                    "--character-easing",
                    null,
                    "EASE",
                    "Easing function to use for launched character movement.",
                    OptionArity.One,
                    "out_sine",
                    ValueParsers.ParseEasingName),
                new OptionSpec(
                    "--final-gradient-stops",
                    null,
                    "COLOR",
                    "Space separated, unquoted, list of colors for the final color gradient.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseColorArg,
                    DefaultValues: ["FFA15C", "44D492"]),
                new OptionSpec(
                    "--final-gradient-steps",
                    null,
                    "STEPS",
                    "Number of gradient steps to use.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseGradientSteps,
                    DefaultValues: ["12"]),
                new OptionSpec(
                    "--final-gradient-direction",
                    null,
                    "DIRECTION",
                    "Direction of the final gradient.",
                    OptionArity.One,
                    "radial",
                    ValueParsers.ParseGradientDirection),
            ],
            OrbittingVolley.FromOptions),
        new EffectSpec(
            "overflow",
            "Input text overflows and scrolls the terminal in a random order until eventually appearing ordered.",
            [
                new OptionSpec(
                    "--overflow-gradient-stops",
                    null,
                    "COLOR",
                    "Space separated, unquoted, list of colors for the overflow gradient.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseColorArg,
                    DefaultValues: ["f2ebc0", "8dbfb3", "f2ebc0"]),
                new OptionSpec(
                    "--overflow-cycles-range",
                    null,
                    "RANGE",
                    "Number of cycles to overflow the text.",
                    OptionArity.One,
                    "2-4",
                    ValueParsers.ParsePositiveIntRange),
                new OptionSpec(
                    "--overflow-speed",
                    null,
                    "SPEED",
                    "Speed of the overflow effect.",
                    OptionArity.One,
                    "3",
                    ValueParsers.ParseCommonPositiveInt),
                new OptionSpec(
                    "--final-gradient-stops",
                    null,
                    "COLOR",
                    "Space separated, unquoted, list of colors for the final color gradient.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseColorArg,
                    DefaultValues: ["8A008A", "00D1FF", "FFFFFF"]),
                new OptionSpec(
                    "--final-gradient-steps",
                    null,
                    "STEPS",
                    "Number of gradient steps to use.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseGradientSteps,
                    DefaultValues: ["12"]),
                new OptionSpec(
                    "--final-gradient-direction",
                    null,
                    "DIRECTION",
                    "Direction of the final gradient.",
                    OptionArity.One,
                    "vertical",
                    ValueParsers.ParseGradientDirection),
            ],
            Overflow.FromOptions),
        new EffectSpec(
            "pour",
            "Pours the characters into position from the given direction.",
            [
                new OptionSpec(
                    "--pour-direction",
                    null,
                    "DIRECTION",
                    "Direction the text will pour.",
                    OptionArity.One,
                    "down",
                    Pour.ParsePourDirection),
                new OptionSpec(
                    "--pour-speed",
                    null,
                    "SPEED",
                    "Number of characters poured in per tick. Increase to speed up the effect.",
                    OptionArity.One,
                    "2",
                    ValueParsers.ParseCommonPositiveInt),
                new OptionSpec(
                    "--movement-speed-range",
                    null,
                    "RANGE",
                    "Movement speed range of the characters.",
                    OptionArity.One,
                    "0.4-0.6",
                    ValueParsers.ParsePositiveFloatRange),
                new OptionSpec(
                    "--gap",
                    null,
                    "GAP",
                    "Number of frames to wait between each character in the pour effect.",
                    OptionArity.One,
                    "1",
                    ValueParsers.ParseCommonNonNegativeInt),
                new OptionSpec(
                    "--starting-color",
                    null,
                    "COLOR",
                    "Color of the characters before the gradient starts.",
                    OptionArity.One,
                    "ffffff",
                    ValueParsers.ParseColorArg),
                new OptionSpec(
                    "--final-gradient-stops",
                    null,
                    "COLOR",
                    "Space separated, unquoted, list of colors for the character gradient.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseColorArg,
                    DefaultValues: ["8A008A", "00D1FF", "FFFFFF"]),
                new OptionSpec(
                    "--final-gradient-steps",
                    null,
                    "STEPS",
                    "Number of gradient steps to use.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseGradientSteps,
                    DefaultValues: ["12"]),
                new OptionSpec(
                    "--final-gradient-frames",
                    null,
                    "FRAMES",
                    "Number of frames to display each gradient step.",
                    OptionArity.One,
                    "6",
                    ValueParsers.ParseI64Object),
                new OptionSpec(
                    "--final-gradient-direction",
                    null,
                    "DIRECTION",
                    "Direction of the final gradient.",
                    OptionArity.One,
                    "vertical",
                    ValueParsers.ParseGradientDirection),
                new OptionSpec(
                    "--movement-easing",
                    null,
                    "EASE",
                    "Easing function to use for character movement.",
                    OptionArity.One,
                    "in_quad",
                    ValueParsers.ParseEasingName),
            ],
            Pour.FromOptions),
        new EffectSpec(
            "print",
            "Lines are printed one at a time following a print head. Print head performs line feed, carriage return.",
            [
                new OptionSpec(
                    "--print-head-return-speed",
                    null,
                    "SPEED",
                    "Speed of the print head when performing a carriage return.",
                    OptionArity.One,
                    "1.5",
                    ValueParsers.ParsePositiveFloat),
                new OptionSpec(
                    "--print-speed",
                    null,
                    "SPEED",
                    "Speed of the print head when printing characters.",
                    OptionArity.One,
                    "2",
                    ValueParsers.ParseCommonPositiveInt),
                new OptionSpec(
                    "--print-head-easing",
                    null,
                    "EASE",
                    "Easing function to use for print head movement.",
                    OptionArity.One,
                    "in_out_quad",
                    ValueParsers.ParseEasingName),
                new OptionSpec(
                    "--final-gradient-stops",
                    null,
                    "COLOR",
                    "Space separated, unquoted, list of colors for the final color gradient.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseColorArg,
                    DefaultValues: ["02b8bd", "c1f0e3", "00ffa0"]),
                new OptionSpec(
                    "--final-gradient-steps",
                    null,
                    "STEPS",
                    "Number of gradient steps to use.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseGradientSteps,
                    DefaultValues: ["12"]),
                new OptionSpec(
                    "--final-gradient-direction",
                    null,
                    "DIRECTION",
                    "Direction of the final gradient.",
                    OptionArity.One,
                    "diagonal",
                    ValueParsers.ParseGradientDirection),
            ],
            PrintEffect.FromOptions),
        new EffectSpec(
            "rain",
            "Rain characters from the top of the canvas.",
            [
                new OptionSpec(
                    "--rain-colors",
                    null,
                    "COLOR",
                    "List of colors for the rain drops. Colors are randomly chosen from the list.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseColorArg,
                    DefaultValues: ["00315C", "004C8F", "0075DB", "3F91D9", "78B9F2", "9AC8F5", "B8D8F8", "E3EFFC"]),
                new OptionSpec(
                    "--movement-speed",
                    null,
                    "RANGE",
                    "Falling speed range of the rain drops.",
                    OptionArity.One,
                    "0.33-0.57",
                    ValueParsers.ParsePositiveFloatRange),
                new OptionSpec(
                    "--rain-symbols",
                    null,
                    "SYMBOL",
                    "Space separated list of symbols to use for the rain drops. Symbols are randomly chosen from the list.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseSymbol,
                    DefaultValues: ["o", ".", ",", "*", "|"]),
                new OptionSpec(
                    "--final-gradient-stops",
                    null,
                    "COLOR",
                    "Space separated, unquoted, list of colors for the final color gradient.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseColorArg,
                    DefaultValues: ["488bff", "b2e7de", "57eaf7"]),
                new OptionSpec(
                    "--final-gradient-steps",
                    null,
                    "STEPS",
                    "Number of gradient steps to use.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseGradientSteps,
                    DefaultValues: ["12"]),
                new OptionSpec(
                    "--final-gradient-direction",
                    null,
                    "DIRECTION",
                    "Direction of the final gradient.",
                    OptionArity.One,
                    "diagonal",
                    ValueParsers.ParseGradientDirection),
                new OptionSpec(
                    "--movement-easing",
                    null,
                    "EASE",
                    "Easing function to use for character movement.",
                    OptionArity.One,
                    "in_quart",
                    ValueParsers.ParseEasingName),
            ],
            Rain.FromOptions),
        new EffectSpec(
            "randomsequence",
            "Prints the input data in a random sequence.",
            [
                new OptionSpec(
                    "--speed",
                    null,
                    "SPEED",
                    "Speed of the animation as a percentage of the total number of characters to reveal in each tick.",
                    OptionArity.One,
                    "0.007",
                    ValueParsers.ParsePositiveFloat),
                new OptionSpec(
                    "--final-gradient-stops",
                    null,
                    "COLOR",
                    "Space separated, unquoted, list of colors for the final gradient.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseColorArg,
                    DefaultValues: ["8A008A", "00D1FF", "FFFFFF"]),
                new OptionSpec(
                    "--final-gradient-steps",
                    null,
                    "STEPS",
                    "Number of gradient steps to use.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseGradientSteps,
                    DefaultValues: ["12"]),
                new OptionSpec(
                    "--final-gradient-frames",
                    null,
                    "FRAMES",
                    "Number of frames to display each gradient step.",
                    OptionArity.One,
                    "8",
                    ValueParsers.ParseI64Object),
                new OptionSpec(
                    "--final-gradient-direction",
                    null,
                    "DIRECTION",
                    "Direction of the final gradient.",
                    OptionArity.One,
                    "vertical",
                    ValueParsers.ParseGradientDirection),
            ],
            RandomSequence.FromOptions),
        new EffectSpec(
            "rings",
            "Characters are dispersed and form into spinning rings.",
            [
                new OptionSpec(
                    "--ring-colors",
                    null,
                    "COLOR",
                    "Space separated, unquoted, list of colors for the rings.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseColorArg,
                    DefaultValues: ["ab48ff", "e7b2b2", "fffebd"]),
                new OptionSpec(
                    "--ring-gap",
                    null,
                    "GAP",
                    "Distance between rings as a percent of the smallest canvas dimension.",
                    OptionArity.One,
                    "0.1",
                    ValueParsers.ParsePositiveFloat),
                new OptionSpec(
                    "--spin-duration",
                    null,
                    "DURATION",
                    "Number of frames for each cycle of the spin phase.",
                    OptionArity.One,
                    "200",
                    ValueParsers.ParseCommonPositiveInt),
                new OptionSpec(
                    "--spin-speed",
                    null,
                    "RANGE",
                    "Range of speeds for the rotation of the rings. The speed is randomly selected from this range for each ring.",
                    OptionArity.One,
                    "0.25-1.0",
                    ValueParsers.ParsePositiveFloatRange),
                new OptionSpec(
                    "--disperse-duration",
                    null,
                    "DURATION",
                    "Number of frames spent in the dispersed state between spinning cycles.",
                    OptionArity.One,
                    "200",
                    ValueParsers.ParseCommonPositiveInt),
                new OptionSpec(
                    "--spin-disperse-cycles",
                    null,
                    "CYCLES",
                    "Number of times the animation will cycles between spinning rings and dispersed characters.",
                    OptionArity.One,
                    "3",
                    ValueParsers.ParseCommonPositiveInt),
                new OptionSpec(
                    "--final-gradient-stops",
                    null,
                    "COLOR",
                    "Space separated, unquoted, list of colors for the final color gradient.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseColorArg,
                    DefaultValues: ["ab48ff", "e7b2b2", "fffebd"]),
                new OptionSpec(
                    "--final-gradient-steps",
                    null,
                    "STEPS",
                    "Number of gradient steps to use.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseGradientSteps,
                    DefaultValues: ["12"]),
                new OptionSpec(
                    "--final-gradient-direction",
                    null,
                    "DIRECTION",
                    "Direction of the final gradient.",
                    OptionArity.One,
                    "vertical",
                    ValueParsers.ParseGradientDirection),
            ],
            Rings.FromOptions),
        new EffectSpec(
            "scattered",
            "Text is scattered across the canvas and moves into position.",
            [
                new OptionSpec(
                    "--movement-speed",
                    null,
                    "SPEED",
                    "Movement speed of the characters.",
                    OptionArity.One,
                    "0.5",
                    ValueParsers.ParsePositiveFloat),
                new OptionSpec(
                    "--movement-easing",
                    null,
                    "EASE",
                    "Easing function to use for character movement.",
                    OptionArity.One,
                    "in_out_back",
                    ValueParsers.ParseEasingName),
                new OptionSpec(
                    "--final-gradient-stops",
                    null,
                    "COLOR",
                    "Space separated, unquoted, list of colors for the character gradient.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseColorArg,
                    DefaultValues: ["ff9048", "ab9dff", "bdffea"]),
                new OptionSpec(
                    "--final-gradient-steps",
                    null,
                    "STEPS",
                    "Number of gradient steps to use.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseGradientSteps,
                    DefaultValues: ["12"]),
                new OptionSpec(
                    "--final-gradient-frames",
                    null,
                    "FRAMES",
                    "Number of frames to display each gradient step.",
                    OptionArity.One,
                    "9",
                    ValueParsers.ParseI64Object),
                new OptionSpec(
                    "--final-gradient-direction",
                    null,
                    "DIRECTION",
                    "Direction of the final gradient.",
                    OptionArity.One,
                    "vertical",
                    ValueParsers.ParseGradientDirection),
            ],
            Scattered.FromOptions),
        new EffectSpec(
            "slice",
            "Slices the input in half and slides it into place from opposite directions.",
            [
                new OptionSpec(
                    "--slice-direction",
                    null,
                    "DIRECTION",
                    "Direction of the slice.",
                    OptionArity.One,
                    "vertical",
                    Slice.ParseSliceDirection),
                new OptionSpec(
                    "--movement-speed",
                    null,
                    "SPEED",
                    "Movement speed of the characters.",
                    OptionArity.One,
                    "0.25",
                    ValueParsers.ParsePositiveFloat),
                new OptionSpec(
                    "--movement-easing",
                    null,
                    "EASE",
                    "Easing function to use for character movement.",
                    OptionArity.One,
                    "in_out_expo",
                    ValueParsers.ParseEasingName),
                new OptionSpec(
                    "--final-gradient-stops",
                    null,
                    "COLOR",
                    "Space separated, unquoted, list of colors for the final color gradient.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseColorArg,
                    DefaultValues: ["8A008A", "00D1FF", "FFFFFF"]),
                new OptionSpec(
                    "--final-gradient-steps",
                    null,
                    "STEPS",
                    "Number of gradient steps to use.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseGradientSteps,
                    DefaultValues: ["12"]),
                new OptionSpec(
                    "--final-gradient-direction",
                    null,
                    "DIRECTION",
                    "Direction of the final gradient.",
                    OptionArity.One,
                    "diagonal",
                    ValueParsers.ParseGradientDirection),
            ],
            Slice.FromOptions),
        new EffectSpec(
            "slide",
            "Slide characters into view from outside the terminal.",
            [
                new OptionSpec(
                    "--movement-speed",
                    null,
                    "SPEED",
                    "Speed of the characters.",
                    OptionArity.One,
                    "0.8",
                    ValueParsers.ParsePositiveFloat),
                new OptionSpec(
                    "--grouping",
                    null,
                    "GROUP",
                    "Direction to group characters.",
                    OptionArity.One,
                    "row",
                    Slide.ParseSlideGrouping),
                new OptionSpec(
                    "--gap",
                    null,
                    "GAP",
                    "Number of frames to wait before adding the next group of characters.",
                    OptionArity.One,
                    "2",
                    ValueParsers.ParseCommonNonNegativeInt),
                new OptionSpec(
                    "--reverse-direction",
                    null,
                    "",
                    "Reverse the direction of the characters.",
                    OptionArity.Flag,
                    null,
                    _ => true),
                new OptionSpec(
                    "--merge",
                    null,
                    "",
                    "Merge the character groups originating from either side of the terminal.",
                    OptionArity.Flag,
                    null,
                    _ => true),
                new OptionSpec(
                    "--movement-easing",
                    null,
                    "EASE",
                    "Easing function to use for character movement.",
                    OptionArity.One,
                    "in_out_quad",
                    ValueParsers.ParseEasingName),
                new OptionSpec(
                    "--final-gradient-stops",
                    null,
                    "COLOR",
                    "Space separated, unquoted, list of colors for the character gradient.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseColorArg,
                    DefaultValues: ["833ab4", "fd1d1d", "fcb045"]),
                new OptionSpec(
                    "--final-gradient-steps",
                    null,
                    "STEPS",
                    "Number of gradient steps to use.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseGradientSteps,
                    DefaultValues: ["12"]),
                new OptionSpec(
                    "--final-gradient-frames",
                    null,
                    "FRAMES",
                    "Number of frames to display each gradient step.",
                    OptionArity.One,
                    "6",
                    ValueParsers.ParseI64Object),
                new OptionSpec(
                    "--final-gradient-direction",
                    null,
                    "DIRECTION",
                    "Direction of the gradient.",
                    OptionArity.One,
                    "vertical",
                    ValueParsers.ParseGradientDirection),
            ],
            Slide.FromOptions),
        Stub("smoke", "Smoke floods the canvas colorizing any characters it crosses."),
        new EffectSpec(
            "spotlights",
            "Spotlights search the text area, illuminating characters, before converging in the center and expanding.",
            [
                new OptionSpec(
                    "--beam-width-ratio",
                    null,
                    "RATIO",
                    "Width of the beam of light as min(width, height) // n of the input text. Values less than 1 are raised to 1.",
                    OptionArity.One,
                    "2.0",
                    ValueParsers.ParsePositiveFloat),
                new OptionSpec(
                    "--beam-falloff",
                    null,
                    "FALLOFF",
                    "Distance from the edge of the beam where the brightness begins to fall off, as a percentage of total beam width.",
                    OptionArity.One,
                    "0.3",
                    ValueParsers.ParseNonNegativeFloat),
                new OptionSpec(
                    "--search-duration",
                    null,
                    "DURATION",
                    "Duration of the search phase, in frames, before the spotlights converge in the center.",
                    OptionArity.One,
                    "550",
                    ValueParsers.ParseCommonPositiveInt),
                new OptionSpec(
                    "--search-speed-range",
                    null,
                    "RANGE",
                    "Range of speeds for the spotlights during the search phase.",
                    OptionArity.One,
                    "0.35-0.75",
                    ValueParsers.ParsePositiveFloatRange),
                new OptionSpec(
                    "--spotlight-count",
                    null,
                    "COUNT",
                    "Number of spotlights to use.",
                    OptionArity.One,
                    "3",
                    ValueParsers.ParseCommonPositiveInt),
                new OptionSpec(
                    "--final-gradient-stops",
                    null,
                    "COLOR",
                    "Space separated, unquoted, list of colors for the final color gradient.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseColorArg,
                    DefaultValues: ["ab48ff", "e7b2b2", "fffebd"]),
                new OptionSpec(
                    "--final-gradient-steps",
                    null,
                    "STEPS",
                    "Number of gradient steps to use.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseGradientSteps,
                    DefaultValues: ["12"]),
                new OptionSpec(
                    "--final-gradient-direction",
                    null,
                    "DIRECTION",
                    "Direction of the final gradient.",
                    OptionArity.One,
                    "vertical",
                    ValueParsers.ParseGradientDirection),
            ],
            Spotlights.FromOptions),
        new EffectSpec(
            "spray",
            "Draws the characters spawning at varying rates from a single point.",
            [
                new OptionSpec(
                    "--spray-position",
                    null,
                    "POSITION",
                    "Position for the spray origin.",
                    OptionArity.One,
                    "e",
                    Spray.ParseSprayPosition),
                new OptionSpec(
                    "--spray-volume",
                    null,
                    "VOLUME",
                    "Number of characters to spray per tick as a percent of the total number of characters.",
                    OptionArity.One,
                    "0.005",
                    ValueParsers.ParsePositiveRatio),
                new OptionSpec(
                    "--movement-speed-range",
                    null,
                    "RANGE",
                    "Movement speed range of the characters.",
                    OptionArity.One,
                    "0.6-1.4",
                    ValueParsers.ParsePositiveFloatRange),
                new OptionSpec(
                    "--movement-easing",
                    null,
                    "EASE",
                    "Easing function to use for character movement.",
                    OptionArity.One,
                    "out_expo",
                    ValueParsers.ParseEasingName),
                new OptionSpec(
                    "--final-gradient-stops",
                    null,
                    "COLOR",
                    "Space separated, unquoted, list of colors for the final color gradient.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseColorArg,
                    DefaultValues: ["8A008A", "00D1FF", "FFFFFF"]),
                new OptionSpec(
                    "--final-gradient-steps",
                    null,
                    "STEPS",
                    "Number of gradient steps to use.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseGradientSteps,
                    DefaultValues: ["12"]),
                new OptionSpec(
                    "--final-gradient-direction",
                    null,
                    "DIRECTION",
                    "Direction of the final gradient.",
                    OptionArity.One,
                    "vertical",
                    ValueParsers.ParseGradientDirection),
            ],
            Spray.FromOptions),
        new EffectSpec(
            "swarm",
            "Characters are grouped into swarms and move around the terminal before settling into position.",
            [
                new OptionSpec(
                    "--base-color",
                    null,
                    "COLOR",
                    "Space separated, unquoted, list of colors for the swarms.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseColorArg,
                    DefaultValues: ["31a0d4"]),
                new OptionSpec(
                    "--flash-color",
                    null,
                    "COLOR",
                    "Color for the character flash. Characters flash when moving.",
                    OptionArity.One,
                    "f2ea79",
                    ValueParsers.ParseColorArg),
                new OptionSpec(
                    "--swarm-size",
                    null,
                    "RATIO",
                    "Percent of total characters in each swarm.",
                    OptionArity.One,
                    "0.1",
                    ValueParsers.ParseNonNegativeRatio),
                new OptionSpec(
                    "--swarm-coordination",
                    null,
                    "RATIO",
                    "Percent of characters in a swarm that move as a group.",
                    OptionArity.One,
                    "0.80",
                    ValueParsers.ParseNonNegativeRatio),
                new OptionSpec(
                    "--swarm-area-count-range",
                    null,
                    "RANGE",
                    "Range of the number of areas where characters will swarm.",
                    OptionArity.One,
                    "2-4",
                    ValueParsers.ParsePositiveIntRange),
                new OptionSpec(
                    "--final-gradient-stops",
                    null,
                    "COLOR",
                    "Space separated, unquoted, list of colors for the final color gradient.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseColorArg,
                    DefaultValues: ["31b900", "f0ff65"]),
                new OptionSpec(
                    "--final-gradient-steps",
                    null,
                    "STEPS",
                    "Number of gradient steps to use.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseGradientSteps,
                    DefaultValues: ["12"]),
                new OptionSpec(
                    "--final-gradient-direction",
                    null,
                    "DIRECTION",
                    "Direction of the final gradient.",
                    OptionArity.One,
                    "horizontal",
                    ValueParsers.ParseGradientDirection),
            ],
            Swarm.FromOptions),
        new EffectSpec(
            "sweep",
            "Sweep across the canvas to reveal uncolored text, reverse sweep to color the text.",
            [
                new OptionSpec(
                    "--sweep-symbols",
                    null,
                    "SYMBOL",
                    "Space separated list of symbols to use for the sweep shimmer.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseSymbol,
                    DefaultValues: ["█", "▓", "▒", "░"]),
                new OptionSpec(
                    "--first-sweep-direction",
                    null,
                    "DIRECTION",
                    "Direction of the first sweep, revealing uncolored characters.",
                    OptionArity.One,
                    "column_right_to_left",
                    ValueParsers.ParseCharacterGroup),
                new OptionSpec(
                    "--second-sweep-direction",
                    null,
                    "DIRECTION",
                    "Direction of the second sweep, coloring the characters.",
                    OptionArity.One,
                    "column_left_to_right",
                    ValueParsers.ParseCharacterGroup),
                new OptionSpec(
                    "--final-gradient-stops",
                    null,
                    "COLOR",
                    "Space separated, unquoted, list of colors for the character gradient (applied from bottom to top).",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseColorArg,
                    DefaultValues: ["8A008A", "00D1FF", "ffffff"]),
                new OptionSpec(
                    "--final-gradient-steps",
                    null,
                    "STEPS",
                    "Number of gradient steps to use.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseGradientSteps,
                    DefaultValues: ["8"]),
                new OptionSpec(
                    "--final-gradient-direction",
                    null,
                    "DIRECTION",
                    "Direction of the final gradient.",
                    OptionArity.One,
                    "vertical",
                    ValueParsers.ParseGradientDirection),
            ],
            Sweep.FromOptions),
        Stub("synthgrid", "Create a grid which fills with characters dissolving into the final text."),
        Stub("thunderstorm", "Create a thunderstorm in the terminal."),
        new EffectSpec(
            "unstable",
            "Spawn characters jumbled, explode them to the edge of the canvas, then reassemble them in the correct layout.",
            [
                new OptionSpec(
                    "--unstable-color",
                    null,
                    "COLOR",
                    "Color transitioned to as the characters become unstable.",
                    OptionArity.One,
                    "ff9200",
                    ValueParsers.ParseColorArg),
                new OptionSpec(
                    "--explosion-ease",
                    null,
                    "EASE",
                    "Easing function to use for character movement during the explosion.",
                    OptionArity.One,
                    "out_expo",
                    ValueParsers.ParseEasingName),
                new OptionSpec(
                    "--explosion-speed",
                    null,
                    "SPEED",
                    "Speed of characters during explosion.",
                    OptionArity.One,
                    "1.0",
                    ValueParsers.ParsePositiveFloat),
                new OptionSpec(
                    "--reassembly-ease",
                    null,
                    "EASE",
                    "Easing function to use for character reassembly.",
                    OptionArity.One,
                    "out_expo",
                    ValueParsers.ParseEasingName),
                new OptionSpec(
                    "--reassembly-speed",
                    null,
                    "SPEED",
                    "Speed of characters during reassembly.",
                    OptionArity.One,
                    "1.0",
                    ValueParsers.ParsePositiveFloat),
                new OptionSpec(
                    "--final-gradient-stops",
                    null,
                    "COLOR",
                    "Space separated, unquoted, list of colors for the final color gradient.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseColorArg,
                    DefaultValues: ["8A008A", "00D1FF", "FFFFFF"]),
                new OptionSpec(
                    "--final-gradient-steps",
                    null,
                    "STEPS",
                    "Number of gradient steps to use.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseGradientSteps,
                    DefaultValues: ["12"]),
                new OptionSpec(
                    "--final-gradient-direction",
                    null,
                    "DIRECTION",
                    "Direction of the final gradient.",
                    OptionArity.One,
                    "vertical",
                    ValueParsers.ParseGradientDirection),
            ],
            Unstable.FromOptions),
        Stub("vhstape", "Lines of characters glitch left and right and lose detail like an old VHS tape."),
        new EffectSpec(
            "waves",
            "Waves travel across the terminal leaving behind the characters.",
            [
                new OptionSpec(
                    "--wave-symbols",
                    null,
                    "SYMBOL",
                    "Symbols to use for the wave animation.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseSymbol,
                    DefaultValues: ["▁", "▂", "▃", "▄", "▅", "▆", "▇", "█", "▇", "▆", "▅", "▄", "▃", "▂", "▁"]),
                new OptionSpec(
                    "--wave-gradient-stops",
                    null,
                    "COLOR",
                    "Space separated, unquoted, list of colors for the character gradient (applied across the canvas).",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseColorArg,
                    DefaultValues: ["f0ff65", "ffb102", "31a0d4", "ffb102", "f0ff65"]),
                new OptionSpec(
                    "--wave-gradient-steps",
                    null,
                    "STEPS",
                    "Space separated, unquoted, list of the number of gradient steps to use.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseGradientSteps,
                    DefaultValues: ["6"]),
                new OptionSpec(
                    "--wave-count",
                    null,
                    "COUNT",
                    "Number of waves to generate. n > 0.",
                    OptionArity.One,
                    "7",
                    ValueParsers.ParseCommonPositiveInt),
                new OptionSpec(
                    "--wave-length",
                    null,
                    "LENGTH",
                    "The number of frames for each step of the wave.",
                    OptionArity.One,
                    "2",
                    ValueParsers.ParseCommonPositiveInt),
                new OptionSpec(
                    "--wave-direction",
                    null,
                    "DIRECTION",
                    "Direction of the wave.",
                    OptionArity.One,
                    "column_left_to_right",
                    ValueParsers.ParseWaveDirection),
                new OptionSpec(
                    "--wave-easing",
                    null,
                    "EASE",
                    "Easing function to use for wave travel.",
                    OptionArity.One,
                    "in_out_sine",
                    ValueParsers.ParseEasingName),
                new OptionSpec(
                    "--final-gradient-stops",
                    null,
                    "COLOR",
                    "Space separated, unquoted, list of colors for the final color gradient.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseColorArg,
                    DefaultValues: ["ffb102", "31a0d4", "f0ff65"]),
                new OptionSpec(
                    "--final-gradient-steps",
                    null,
                    "STEPS",
                    "Number of gradient steps to use.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseGradientSteps,
                    DefaultValues: ["12"]),
                new OptionSpec(
                    "--final-gradient-direction",
                    null,
                    "DIRECTION",
                    "Direction of the final gradient.",
                    OptionArity.One,
                    "diagonal",
                    ValueParsers.ParseGradientDirection),
            ],
            Waves.FromOptions),
        new EffectSpec(
            "wipe",
            "Wipes the text across the terminal to reveal characters.",
            [
                new OptionSpec(
                    "--wipe-direction",
                    null,
                    "DIRECTION",
                    "Direction the text will wipe.",
                    OptionArity.One,
                    "diagonal_top_left_to_bottom_right",
                    ValueParsers.ParseCharacterGroup),
                new OptionSpec(
                    "--wipe-delay",
                    null,
                    "DELAY",
                    "Number of frames to wait before adding the next character group.",
                    OptionArity.One,
                    "0",
                    ValueParsers.ParseCommonNonNegativeInt),
                new OptionSpec(
                    "--wipe-ease",
                    null,
                    "EASE",
                    "Easing function to use for the wipe effect.",
                    OptionArity.One,
                    "in_out_circ",
                    ValueParsers.ParseEasingName),
                new OptionSpec(
                    "--final-gradient-stops",
                    null,
                    "COLOR",
                    "Space separated, unquoted, list of colors for the wipe gradient.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseColorArg,
                    DefaultValues: ["833ab4", "fd1d1d", "fcb045"]),
                new OptionSpec(
                    "--final-gradient-steps",
                    null,
                    "STEPS",
                    "Number of gradient steps to use.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseGradientSteps,
                    DefaultValues: ["12"]),
                new OptionSpec(
                    "--final-gradient-frames",
                    null,
                    "FRAMES",
                    "Number of frames to display each gradient step.",
                    OptionArity.One,
                    "3",
                    ValueParsers.ParseI64Object),
                new OptionSpec(
                    "--final-gradient-direction",
                    null,
                    "DIRECTION",
                    "Direction of the final gradient.",
                    OptionArity.One,
                    "vertical",
                    ValueParsers.ParseGradientDirection),
            ],
            Wipe.FromOptions),
    ];

    public static EffectSpec? Find(string name)
    {
        foreach (EffectSpec spec in Effects)
        {
            if (spec.Name == name)
            {
                return spec;
            }
        }

        return null;
    }

    public static bool Contains(string name) => Find(name) is not null;

    private static EffectSpec Stub(string name, string description) =>
        new EffectSpec(name, description, []);
}
