using System;
using System.Collections.Generic;
using Ttfx.Cli;
using Ttfx.Engine;

namespace Ttfx.Effects;

public sealed record EffectSpec(
    string Name,
    string Description,
    OptionSpec[] Options,
    Func<Dictionary<string, object>, IEffect>? Factory = null);

/// <summary>
/// Static name → option specs + factory. Enumeration order is observable:
/// <c>--random-effect</c> selects by <c>ChoiceIndex(names.Count)</c>, so the
/// list matches the reference EffectCommand order exactly.
/// <c>--probe</c> is a root flag, not a registry entry.
/// </summary>
public static class EffectRegistry
{
    public static EffectSpec[] Effects { get; } =
    [
        new EffectSpec(
            "beams",
            "Create beams which travel over the canvas illuminating the characters behind them.",
            [
                new OptionSpec(
                    "--beam-row-symbols",
                    null,
                    "SYMBOL",
                    "Symbols to use for the beam effect when moving along a row.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseSymbol),
                new OptionSpec(
                    "--beam-column-symbols",
                    null,
                    "SYMBOL",
                    "Symbols to use for the beam effect when moving along a column.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseSymbol),
            ]),
        Stub("binarypath", "Binary representations of each character move towards the home coordinate of the character."),
        Stub("blackhole", "Characters are consumed by a black hole and explode outwards."),
        new EffectSpec(
            "bouncyballs",
            "Characters are bouncy balls falling from the top of the canvas.",
            [
                new OptionSpec(
                    "--ball-colors",
                    null,
                    "COLOR",
                    "Space separated list of colors from which ball colors will be randomly selected.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseColorArg,
                    DefaultValues: ["d1f4a5", "96e2a4", "5acda9"]),
                new OptionSpec(
                    "--ball-symbols",
                    null,
                    "SYMBOL",
                    "Space separated list of symbols to use for the balls.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseSymbol,
                    DefaultValues: ["*", "o", "O", "0", "."]),
                new OptionSpec(
                    "--ball-delay",
                    null,
                    "DELAY",
                    "Number of frames between ball drops, increase to reduce ball drop rate.",
                    OptionArity.One,
                    "4",
                    ValueParsers.ParseCommonNonNegativeInt),
                new OptionSpec(
                    "--movement-speed",
                    null,
                    "SPEED",
                    "Movement speed of the characters.",
                    OptionArity.One,
                    "0.45",
                    ValueParsers.ParsePositiveFloat),
                new OptionSpec(
                    "--movement-easing",
                    null,
                    "EASE",
                    "Easing function to use for character movement.",
                    OptionArity.One,
                    "out_bounce",
                    ValueParsers.ParseEasingName),
                new OptionSpec(
                    "--final-gradient-stops",
                    null,
                    "COLOR",
                    "Space separated, unquoted, list of colors for the final color gradient.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseColorArg,
                    DefaultValues: ["f8ffae", "43c6ac"]),
                new OptionSpec(
                    "--final-gradient-steps",
                    null,
                    "STEPS",
                    "Number of gradient steps to use.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseGradientSteps,
                    DefaultValues: ["12"]),
                new OptionSpec(
                    "--final-gradient-direction",
                    null,
                    "DIRECTION",
                    "Direction of the final gradient.",
                    OptionArity.One,
                    "diagonal",
                    ValueParsers.ParseGradientDirection),
            ],
            BouncyBalls.FromOptions),
        Stub("bubbles", "Characters are formed into bubbles that float down and pop."),
        Stub("burn", "Burns vertically in the canvas."),
        Stub("colorshift", "Display a gradient that shifts colors across the terminal."),
        Stub("crumble", "Characters lose color and crumble into dust, vacuumed up, and reformed."),
        Stub("decrypt", "Display a movie style decryption effect."),
        new EffectSpec(
            "errorcorrect",
            "Some characters start in the wrong position and are corrected in sequence.",
            [
                new OptionSpec(
                    "--error-pairs",
                    null,
                    "PAIRS",
                    "Percent of characters that are in the wrong position. This is a float between 0 and 1.0.",
                    OptionArity.One,
                    "0.1",
                    ValueParsers.ParsePositiveFloat),
                new OptionSpec(
                    "--swap-delay",
                    null,
                    "DELAY",
                    "Number of frames between swaps.",
                    OptionArity.One,
                    "6",
                    ValueParsers.ParseCommonPositiveInt),
                new OptionSpec(
                    "--error-color",
                    null,
                    "COLOR",
                    "Color for the characters that are in the wrong position.",
                    OptionArity.One,
                    "e74c3c",
                    ValueParsers.ParseColorArg),
                new OptionSpec(
                    "--correct-color",
                    null,
                    "COLOR",
                    "Color for the characters once corrected, this is a gradient from error-color and fades to final-color.",
                    OptionArity.One,
                    "45bf55",
                    ValueParsers.ParseColorArg),
                new OptionSpec(
                    "--movement-speed",
                    null,
                    "SPEED",
                    "Speed of the characters while moving to the correct position.",
                    OptionArity.One,
                    "0.9",
                    ValueParsers.ParsePositiveFloat),
                new OptionSpec(
                    "--final-gradient-stops",
                    null,
                    "COLOR",
                    "Space separated, unquoted, list of colors for the final color gradient.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseColorArg,
                    DefaultValues: ["8A008A", "00D1FF", "FFFFFF"]),
                new OptionSpec(
                    "--final-gradient-steps",
                    null,
                    "STEPS",
                    "Number of gradient steps to use.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseGradientSteps,
                    DefaultValues: ["12"]),
                new OptionSpec(
                    "--final-gradient-direction",
                    null,
                    "DIRECTION",
                    "Direction of the final gradient.",
                    OptionArity.One,
                    "vertical",
                    ValueParsers.ParseGradientDirection),
            ],
            ErrorCorrect.FromOptions),
        new EffectSpec(
            "expand",
            "Expands the text from a single point.",
            [
                new OptionSpec(
                    "--expand-easing",
                    null,
                    "EASE",
                    "Easing function to use for character movement.",
                    OptionArity.One,
                    "in_out_quart",
                    ValueParsers.ParseEasingName),
                new OptionSpec(
                    "--movement-speed",
                    null,
                    "SPEED",
                    "Movement speed of the characters.",
                    OptionArity.One,
                    "0.35",
                    ValueParsers.ParsePositiveFloat),
                new OptionSpec(
                    "--final-gradient-stops",
                    null,
                    "COLOR",
                    "Space separated, unquoted, list of colors for the final color gradient.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseColorArg,
                    DefaultValues: ["8A008A", "00D1FF", "FFFFFF"]),
                new OptionSpec(
                    "--final-gradient-steps",
                    null,
                    "STEPS",
                    "Number of gradient steps to use.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseGradientSteps,
                    DefaultValues: ["12"]),
                new OptionSpec(
                    "--final-gradient-direction",
                    null,
                    "DIRECTION",
                    "Direction of the final gradient.",
                    OptionArity.One,
                    "vertical",
                    ValueParsers.ParseGradientDirection),
            ],
            Expand.FromOptions),
        Stub("fireworks", "Characters launch and explode like fireworks and fall into place."),
        Stub("highlight", "Run a specular highlight across the text."),
        Stub("laseretch", "A laser etches characters onto the terminal."),
        Stub("matrix", "Matrix digital rain effect."),
        new EffectSpec(
            "middleout",
            "Text expands in a single row or column in the middle of the canvas then out.",
            [
                new OptionSpec(
                    "--starting-color",
                    null,
                    "COLOR",
                    "Color for the initial text in the center of the canvas.",
                    OptionArity.One,
                    "ffffff",
                    ValueParsers.ParseColorArg),
                new OptionSpec(
                    "--expand-direction",
                    null,
                    "DIRECTION",
                    "Direction the text will expand.",
                    OptionArity.One,
                    "vertical",
                    Middleout.ParseExpandDirection),
                new OptionSpec(
                    "--center-movement-speed",
                    null,
                    "SPEED",
                    "Speed of the characters during the initial expansion of the center vertical/horiztonal line.",
                    OptionArity.One,
                    "0.6",
                    ValueParsers.ParsePositiveFloat),
                new OptionSpec(
                    "--full-movement-speed",
                    null,
                    "SPEED",
                    "Speed of the characters during the final full expansion.",
                    OptionArity.One,
                    "0.6",
                    ValueParsers.ParsePositiveFloat),
                new OptionSpec(
                    "--center-easing",
                    null,
                    "EASE",
                    "Easing function to use for initial expansion.",
                    OptionArity.One,
                    "in_out_sine",
                    ValueParsers.ParseEasingName),
                new OptionSpec(
                    "--full-easing",
                    null,
                    "EASE",
                    "Easing function to use for full expansion.",
                    OptionArity.One,
                    "in_out_sine",
                    ValueParsers.ParseEasingName),
                new OptionSpec(
                    "--final-gradient-stops",
                    null,
                    "COLOR",
                    "Space separated, unquoted, list of colors for the final color gradient.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseColorArg,
                    DefaultValues: ["8A008A", "00D1FF", "FFFFFF"]),
                new OptionSpec(
                    "--final-gradient-steps",
                    null,
                    "STEPS",
                    "Number of gradient steps to use.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseGradientSteps,
                    DefaultValues: ["12"]),
                new OptionSpec(
                    "--final-gradient-direction",
                    null,
                    "DIRECTION",
                    "Direction of the final gradient.",
                    OptionArity.One,
                    "vertical",
                    ValueParsers.ParseGradientDirection),
            ],
            Middleout.FromOptions),
        Stub(
            "orbittingvolley",
            "Four launchers orbit the canvas firing volleys of characters inward to build the input text from the center out."),
        Stub(
            "overflow",
            "Input text overflows and scrolls the terminal in a random order until eventually appearing ordered."),
        new EffectSpec(
            "pour",
            "Pours the characters into position from the given direction.",
            [
                new OptionSpec(
                    "--pour-direction",
                    null,
                    "DIRECTION",
                    "Direction the text will pour.",
                    OptionArity.One,
                    "down",
                    Pour.ParsePourDirection),
                new OptionSpec(
                    "--pour-speed",
                    null,
                    "SPEED",
                    "Number of characters poured in per tick. Increase to speed up the effect.",
                    OptionArity.One,
                    "2",
                    ValueParsers.ParseCommonPositiveInt),
                new OptionSpec(
                    "--movement-speed-range",
                    null,
                    "RANGE",
                    "Movement speed range of the characters.",
                    OptionArity.One,
                    "0.4-0.6",
                    ValueParsers.ParsePositiveFloatRange),
                new OptionSpec(
                    "--gap",
                    null,
                    "GAP",
                    "Number of frames to wait between each character in the pour effect.",
                    OptionArity.One,
                    "1",
                    ValueParsers.ParseCommonNonNegativeInt),
                new OptionSpec(
                    "--starting-color",
                    null,
                    "COLOR",
                    "Color of the characters before the gradient starts.",
                    OptionArity.One,
                    "ffffff",
                    ValueParsers.ParseColorArg),
                new OptionSpec(
                    "--final-gradient-stops",
                    null,
                    "COLOR",
                    "Space separated, unquoted, list of colors for the character gradient.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseColorArg,
                    DefaultValues: ["8A008A", "00D1FF", "FFFFFF"]),
                new OptionSpec(
                    "--final-gradient-steps",
                    null,
                    "STEPS",
                    "Number of gradient steps to use.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseGradientSteps,
                    DefaultValues: ["12"]),
                new OptionSpec(
                    "--final-gradient-frames",
                    null,
                    "FRAMES",
                    "Number of frames to display each gradient step.",
                    OptionArity.One,
                    "6",
                    ValueParsers.ParseI64Object),
                new OptionSpec(
                    "--final-gradient-direction",
                    null,
                    "DIRECTION",
                    "Direction of the final gradient.",
                    OptionArity.One,
                    "vertical",
                    ValueParsers.ParseGradientDirection),
                new OptionSpec(
                    "--movement-easing",
                    null,
                    "EASE",
                    "Easing function to use for character movement.",
                    OptionArity.One,
                    "in_quad",
                    ValueParsers.ParseEasingName),
            ],
            Pour.FromOptions),
        Stub("print", "Lines are printed one at a time following a print head. Print head performs line feed, carriage return."),
        new EffectSpec(
            "rain",
            "Rain characters from the top of the canvas.",
            [
                new OptionSpec(
                    "--rain-colors",
                    null,
                    "COLOR",
                    "List of colors for the rain drops. Colors are randomly chosen from the list.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseColorArg,
                    DefaultValues: ["00315C", "004C8F", "0075DB", "3F91D9", "78B9F2", "9AC8F5", "B8D8F8", "E3EFFC"]),
                new OptionSpec(
                    "--movement-speed",
                    null,
                    "RANGE",
                    "Falling speed range of the rain drops.",
                    OptionArity.One,
                    "0.33-0.57",
                    ValueParsers.ParsePositiveFloatRange),
                new OptionSpec(
                    "--rain-symbols",
                    null,
                    "SYMBOL",
                    "Space separated list of symbols to use for the rain drops. Symbols are randomly chosen from the list.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseSymbol,
                    DefaultValues: ["o", ".", ",", "*", "|"]),
                new OptionSpec(
                    "--final-gradient-stops",
                    null,
                    "COLOR",
                    "Space separated, unquoted, list of colors for the final color gradient.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseColorArg,
                    DefaultValues: ["488bff", "b2e7de", "57eaf7"]),
                new OptionSpec(
                    "--final-gradient-steps",
                    null,
                    "STEPS",
                    "Number of gradient steps to use.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseGradientSteps,
                    DefaultValues: ["12"]),
                new OptionSpec(
                    "--final-gradient-direction",
                    null,
                    "DIRECTION",
                    "Direction of the final gradient.",
                    OptionArity.One,
                    "diagonal",
                    ValueParsers.ParseGradientDirection),
                new OptionSpec(
                    "--movement-easing",
                    null,
                    "EASE",
                    "Easing function to use for character movement.",
                    OptionArity.One,
                    "in_quart",
                    ValueParsers.ParseEasingName),
            ],
            Rain.FromOptions),
        new EffectSpec(
            "randomsequence",
            "Prints the input data in a random sequence.",
            [
                new OptionSpec(
                    "--speed",
                    null,
                    "SPEED",
                    "Speed of the animation as a percentage of the total number of characters to reveal in each tick.",
                    OptionArity.One,
                    "0.007",
                    ValueParsers.ParsePositiveFloat),
                new OptionSpec(
                    "--final-gradient-stops",
                    null,
                    "COLOR",
                    "Space separated, unquoted, list of colors for the final gradient.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseColorArg,
                    DefaultValues: ["8A008A", "00D1FF", "FFFFFF"]),
                new OptionSpec(
                    "--final-gradient-steps",
                    null,
                    "STEPS",
                    "Number of gradient steps to use.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseGradientSteps,
                    DefaultValues: ["12"]),
                new OptionSpec(
                    "--final-gradient-frames",
                    null,
                    "FRAMES",
                    "Number of frames to display each gradient step.",
                    OptionArity.One,
                    "8",
                    ValueParsers.ParseI64Object),
                new OptionSpec(
                    "--final-gradient-direction",
                    null,
                    "DIRECTION",
                    "Direction of the final gradient.",
                    OptionArity.One,
                    "vertical",
                    ValueParsers.ParseGradientDirection),
            ],
            RandomSequence.FromOptions),
        Stub("rings", "Characters are dispersed and form into spinning rings."),
        new EffectSpec(
            "scattered",
            "Text is scattered across the canvas and moves into position.",
            [
                new OptionSpec(
                    "--movement-speed",
                    null,
                    "SPEED",
                    "Movement speed of the characters.",
                    OptionArity.One,
                    "0.5",
                    ValueParsers.ParsePositiveFloat),
                new OptionSpec(
                    "--movement-easing",
                    null,
                    "EASE",
                    "Easing function to use for character movement.",
                    OptionArity.One,
                    "in_out_back",
                    ValueParsers.ParseEasingName),
                new OptionSpec(
                    "--final-gradient-stops",
                    null,
                    "COLOR",
                    "Space separated, unquoted, list of colors for the character gradient.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseColorArg,
                    DefaultValues: ["ff9048", "ab9dff", "bdffea"]),
                new OptionSpec(
                    "--final-gradient-steps",
                    null,
                    "STEPS",
                    "Number of gradient steps to use.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseGradientSteps,
                    DefaultValues: ["12"]),
                new OptionSpec(
                    "--final-gradient-frames",
                    null,
                    "FRAMES",
                    "Number of frames to display each gradient step.",
                    OptionArity.One,
                    "9",
                    ValueParsers.ParseI64Object),
                new OptionSpec(
                    "--final-gradient-direction",
                    null,
                    "DIRECTION",
                    "Direction of the final gradient.",
                    OptionArity.One,
                    "vertical",
                    ValueParsers.ParseGradientDirection),
            ],
            Scattered.FromOptions),
        new EffectSpec(
            "slice",
            "Slices the input in half and slides it into place from opposite directions.",
            [
                new OptionSpec(
                    "--slice-direction",
                    null,
                    "DIRECTION",
                    "Direction of the slice.",
                    OptionArity.One,
                    "vertical",
                    Slice.ParseSliceDirection),
                new OptionSpec(
                    "--movement-speed",
                    null,
                    "SPEED",
                    "Movement speed of the characters.",
                    OptionArity.One,
                    "0.25",
                    ValueParsers.ParsePositiveFloat),
                new OptionSpec(
                    "--movement-easing",
                    null,
                    "EASE",
                    "Easing function to use for character movement.",
                    OptionArity.One,
                    "in_out_expo",
                    ValueParsers.ParseEasingName),
                new OptionSpec(
                    "--final-gradient-stops",
                    null,
                    "COLOR",
                    "Space separated, unquoted, list of colors for the final color gradient.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseColorArg,
                    DefaultValues: ["8A008A", "00D1FF", "FFFFFF"]),
                new OptionSpec(
                    "--final-gradient-steps",
                    null,
                    "STEPS",
                    "Number of gradient steps to use.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseGradientSteps,
                    DefaultValues: ["12"]),
                new OptionSpec(
                    "--final-gradient-direction",
                    null,
                    "DIRECTION",
                    "Direction of the final gradient.",
                    OptionArity.One,
                    "diagonal",
                    ValueParsers.ParseGradientDirection),
            ],
            Slice.FromOptions),
        new EffectSpec(
            "slide",
            "Slide characters into view from outside the terminal.",
            [
                new OptionSpec(
                    "--movement-speed",
                    null,
                    "SPEED",
                    "Speed of the characters.",
                    OptionArity.One,
                    "0.8",
                    ValueParsers.ParsePositiveFloat),
                new OptionSpec(
                    "--grouping",
                    null,
                    "GROUP",
                    "Direction to group characters.",
                    OptionArity.One,
                    "row",
                    Slide.ParseSlideGrouping),
                new OptionSpec(
                    "--gap",
                    null,
                    "GAP",
                    "Number of frames to wait before adding the next group of characters.",
                    OptionArity.One,
                    "2",
                    ValueParsers.ParseCommonNonNegativeInt),
                new OptionSpec(
                    "--reverse-direction",
                    null,
                    "",
                    "Reverse the direction of the characters.",
                    OptionArity.Flag,
                    null,
                    _ => true),
                new OptionSpec(
                    "--merge",
                    null,
                    "",
                    "Merge the character groups originating from either side of the terminal.",
                    OptionArity.Flag,
                    null,
                    _ => true),
                new OptionSpec(
                    "--movement-easing",
                    null,
                    "EASE",
                    "Easing function to use for character movement.",
                    OptionArity.One,
                    "in_out_quad",
                    ValueParsers.ParseEasingName),
                new OptionSpec(
                    "--final-gradient-stops",
                    null,
                    "COLOR",
                    "Space separated, unquoted, list of colors for the character gradient.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseColorArg,
                    DefaultValues: ["833ab4", "fd1d1d", "fcb045"]),
                new OptionSpec(
                    "--final-gradient-steps",
                    null,
                    "STEPS",
                    "Number of gradient steps to use.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseGradientSteps,
                    DefaultValues: ["12"]),
                new OptionSpec(
                    "--final-gradient-frames",
                    null,
                    "FRAMES",
                    "Number of frames to display each gradient step.",
                    OptionArity.One,
                    "6",
                    ValueParsers.ParseI64Object),
                new OptionSpec(
                    "--final-gradient-direction",
                    null,
                    "DIRECTION",
                    "Direction of the gradient.",
                    OptionArity.One,
                    "vertical",
                    ValueParsers.ParseGradientDirection),
            ],
            Slide.FromOptions),
        Stub("smoke", "Smoke floods the canvas colorizing any characters it crosses."),
        Stub(
            "spotlights",
            "Spotlights search the text area, illuminating characters, before converging in the center and expanding."),
        new EffectSpec(
            "spray",
            "Draws the characters spawning at varying rates from a single point.",
            [
                new OptionSpec(
                    "--spray-position",
                    null,
                    "POSITION",
                    "Position for the spray origin.",
                    OptionArity.One,
                    "e",
                    Spray.ParseSprayPosition),
                new OptionSpec(
                    "--spray-volume",
                    null,
                    "VOLUME",
                    "Number of characters to spray per tick as a percent of the total number of characters.",
                    OptionArity.One,
                    "0.005",
                    ValueParsers.ParsePositiveRatio),
                new OptionSpec(
                    "--movement-speed-range",
                    null,
                    "RANGE",
                    "Movement speed range of the characters.",
                    OptionArity.One,
                    "0.6-1.4",
                    ValueParsers.ParsePositiveFloatRange),
                new OptionSpec(
                    "--movement-easing",
                    null,
                    "EASE",
                    "Easing function to use for character movement.",
                    OptionArity.One,
                    "out_expo",
                    ValueParsers.ParseEasingName),
                new OptionSpec(
                    "--final-gradient-stops",
                    null,
                    "COLOR",
                    "Space separated, unquoted, list of colors for the final color gradient.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseColorArg,
                    DefaultValues: ["8A008A", "00D1FF", "FFFFFF"]),
                new OptionSpec(
                    "--final-gradient-steps",
                    null,
                    "STEPS",
                    "Number of gradient steps to use.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseGradientSteps,
                    DefaultValues: ["12"]),
                new OptionSpec(
                    "--final-gradient-direction",
                    null,
                    "DIRECTION",
                    "Direction of the final gradient.",
                    OptionArity.One,
                    "vertical",
                    ValueParsers.ParseGradientDirection),
            ],
            Spray.FromOptions),
        Stub("swarm", "Characters are grouped into swarms and move around the terminal before settling into position."),
        Stub("sweep", "Sweep across the canvas to reveal uncolored text, reverse sweep to color the text."),
        Stub("synthgrid", "Create a grid which fills with characters dissolving into the final text."),
        Stub("thunderstorm", "Create a thunderstorm in the terminal."),
        Stub(
            "unstable",
            "Spawn characters jumbled, explode them to the edge of the canvas, then reassemble them in the correct layout."),
        Stub("vhstape", "Lines of characters glitch left and right and lose detail like an old VHS tape."),
        Stub("waves", "Waves travel across the terminal leaving behind the characters."),
        new EffectSpec(
            "wipe",
            "Wipes the text across the terminal to reveal characters.",
            [
                new OptionSpec(
                    "--wipe-direction",
                    null,
                    "DIRECTION",
                    "Direction the text will wipe.",
                    OptionArity.One,
                    "diagonal_top_left_to_bottom_right",
                    ValueParsers.ParseCharacterGroup),
                new OptionSpec(
                    "--wipe-delay",
                    null,
                    "DELAY",
                    "Number of frames to wait before adding the next character group.",
                    OptionArity.One,
                    "0",
                    ValueParsers.ParseCommonNonNegativeInt),
                new OptionSpec(
                    "--wipe-ease",
                    null,
                    "EASE",
                    "Easing function to use for the wipe effect.",
                    OptionArity.One,
                    "in_out_circ",
                    ValueParsers.ParseEasingName),
                new OptionSpec(
                    "--final-gradient-stops",
                    null,
                    "COLOR",
                    "Space separated, unquoted, list of colors for the wipe gradient.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseColorArg,
                    DefaultValues: ["833ab4", "fd1d1d", "fcb045"]),
                new OptionSpec(
                    "--final-gradient-steps",
                    null,
                    "STEPS",
                    "Number of gradient steps to use.",
                    OptionArity.AtLeastOne,
                    null,
                    ValueParsers.ParseGradientSteps,
                    DefaultValues: ["12"]),
                new OptionSpec(
                    "--final-gradient-frames",
                    null,
                    "FRAMES",
                    "Number of frames to display each gradient step.",
                    OptionArity.One,
                    "3",
                    ValueParsers.ParseI64Object),
                new OptionSpec(
                    "--final-gradient-direction",
                    null,
                    "DIRECTION",
                    "Direction of the final gradient.",
                    OptionArity.One,
                    "vertical",
                    ValueParsers.ParseGradientDirection),
            ],
            Wipe.FromOptions),
    ];

    public static EffectSpec? Find(string name)
    {
        foreach (EffectSpec spec in Effects)
        {
            if (spec.Name == name)
            {
                return spec;
            }
        }

        return null;
    }

    public static bool Contains(string name) => Find(name) is not null;

    private static EffectSpec Stub(string name, string description) =>
        new EffectSpec(name, description, []);
}
